src/objects/Employee__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EmployeeRecords.cls
public class EmployeeRecords {
    public EmployeeRecords() {
        //Insert Employee Records
        Employee__c employee = new Employee__c();
        employee.Name = 'Aryan Sharma';
        employee.First_Name__c = 'Aryan';
        employee.Last_Name__c = 'Sharma';
        employee.Project__c = 'Proj';
        employee.Email__c = 'as123@gmail.com';
        
        insert employee;
        
    }
    
}